# Generated by Django 5.0.1 on 2024-06-08 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_lastpage_page_delete_pages_book_author_book_pdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('', 'Не читал'), ('reading', 'Читаю'), ('read', 'Прочитал')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_book', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.genre')),
            ],
            options={
                'unique_together': {('book', 'genre')},
            },
        ),
    ]
