# Generated by Django 5.0.1 on 2024-06-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_lastpage_page_delete_pages_book_author_book_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
