# Generated by Django 5.0.1 on 2024-06-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_alter_book_image_alter_page_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
    ]
