# Generated by Django 5.0.1 on 2024-06-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_alter_book_author_bookrating_favoritebook_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookfeedback',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='favoritebook',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('', ''), ('reading', 'reading'), ('read', 'read')], default='', max_length=10),
        ),
    ]
