# Generated by Django 5.0.1 on 2024-06-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_alter_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['page_number']},
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_pages',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('book', 'page_number')},
        ),
    ]
